spring:
  application:
    name: user-service
  zipkin:
#    baseUrl: http://localhost:9411
        baseUrl: http://localhost:10483
  database:
    driverClassName: org.h2.Driver
  datasource:
    password: ''
    url: jdbc:h2:tcp://localhost:1521/test;INIT=RUNSCRIPT FROM '/opt/h2-data/init.sql';
    username: sa
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true


server:
  port: 8083

