services:
  database:
    build: .
    ports:
      - "81:81"
      - "1521:1521"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: "exit 0"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      backend:
        aliases:
          - "zipkin"

  jaeger:
    image: jaegertracing/all-in-one:1.26
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      # ui
      - 10480:16686
      # jaeger-collector HTTP
      - 10482:14268
      # jaeger-collector UDP
      - 10484:6831/udp
      # zipkin collector
      - 10483:9411
    networks:
      backend:
        aliases:
          - "jaeger"


networks:
  backend:
    driver: bridge