spring:
  application:
    name: ordering-service
  zipkin:
#    baseUrl: http://localhost:9411
        baseUrl: http://localhost:10483
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017


server:
  port: 8081

logging:
  level:
    root: INFO
    com.godle.presentation.tracing: DEBUG

